default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV.fetch('POSTGRES_PORT_5432_TCP_ADDR') %>
  port: <%= ENV.fetch('POSTGRES_PORT_5432_TCP_PORT') %>
  database: <%= ENV.fetch('POSTGRES_ENV_POSTGRES_DB') %>
  username: <%= ENV.fetch('POSTGRES_ENV_POSTGRES_USER') %>
  password: <%= ENV.fetch('POSTGRES_ENV_POSTGRES_PASSWORD') %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: portfolio_development

test:
  <<: *default
  database: portfolio_test

production:
  <<: *default
